version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13.4
    working_directory: /go/src/github.com/MerAuctions/MerAuctions
    steps:
      - checkout
      - run: make build
  test:
    docker:
      - image: circleci/golang:1.13.4
    working_directory: /go/src/github.com/MerAuctions/MerAuctions
    steps:
      - checkout
      - run: make test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test