apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
<<<<<<< HEAD
 name: mongodb-set
=======
 name: mongo
>>>>>>> dfc2d322ee3975788fb18d114473242fda859b8b
spec:
 serviceName: "mongo"
 replicas: 1
 template:
   metadata:
     labels:
       role: mongo
       environment: test
   spec:
     terminationGracePeriodSeconds: 10
     containers:
       - name: mongo
         image: mongo:4.2
         command:
           - mongod
<<<<<<< HEAD
=======
           - "--replSet"
           - rs0
>>>>>>> dfc2d322ee3975788fb18d114473242fda859b8b
         ports:
          - containerPort: 27017
            name: mongodb-port
         volumeMounts:
           - name: mongo-persistent-storage
             mountPath: /data/db
       - name: mongo-sidecar
         image: cvallance/mongo-k8s-sidecar
         env:
           - name: MONGO_SIDECAR_POD_LABELS
             value: "role=mongo,environment=test"
 volumeClaimTemplates:
 - metadata:
     name: mongo-persistent-storage
   spec:
     accessModes: [ "ReadWriteOnce" ]
     resources:
       requests:
         storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
 name: mongo
 labels:
   name: mongo
spec:
 ports:
 - port: 27017
   targetPort: mongodb-port
 clusterIP: None
 selector:
   role: mongo