apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
 name: mongodb-set
spec:
 serviceName: "mongo"
 replicas: 1
 template:
   metadata:
     labels:
       role: mongo
       environment: test
   spec:
     terminationGracePeriodSeconds: 10
     containers:
       - name: mongo
         image: mongo:4.2
         resources:
           limits:
             memory: "350Mi"
             cpu: "300m"
         command:
           - mongod
         ports:
          - containerPort: 27017
            name: mongodb-port
         volumeMounts:
           - name: mongo-persistent-storage
             mountPath: /data/db
       - name: mongo-sidecar
         image: cvallance/mongo-k8s-sidecar
         resources:
           limits:
             memory: "200Mi"
             cpu: "200m"
         env:
           - name: MONGO_SIDECAR_POD_LABELS
             value: "role=mongo,environment=test"
 volumeClaimTemplates:
 - metadata:
     name: mongo-persistent-storage
   spec:
     accessModes: [ "ReadWriteOnce" ]
     resources:
       requests:
         storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
 name: mongo
 labels:
   name: mongo
spec:
 ports:
 - port: 27017
   targetPort: mongodb-port
 clusterIP: None
 selector:
   role: mongo